#!/bin/bash


#text colors

red=$(tput setaf 1)
green=$(tput setaf 2)
yellow=$(tput setaf 3)
blue=$(tput setaf 4)
pink=$(tput setaf 5)
cyan=$(tput setaf 6)
white=$(tput setaf 7)


bt=$(tput bold 2)
#reset color

reset=$(tput sgr0)

#decoration


#background colors
rbg=$(tput setab 1)
wbg=$(tput setab 7)
bbg=$(tput setab 4)
cbg=$(tput setab 6)
gbg=$(tput setab 2)








#clean Terminal
cd
clear

#banner for shadow


echo "${red}░██████╗██╗░░██╗░█████╗░██████╗░░█████╗░░██╗░░░░░░░██╗"
echo "${red}██╔════╝██║░░██║██╔══██╗██╔══██╗██╔══██╗░██║░░██╗░░██║"
echo "${red}╚█████╗░███████║███████║██║░░██║██║░░██║░╚██╗████╗██╔╝"
echo "${red}░╚═══██╗██╔══██║██╔══██║██║░░██║██║░░██║░░████╔═████║░"
echo "${red}██████╔╝██║░░██║██║░░██║██████╔╝╚█████╔╝░░╚██╔╝░╚██╔╝░"
echo "${red}╚═════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═════╝░░╚════╝░░░░╚═╝░░░╚═╝░░"
echo "     ${bt} ${blue}${wbg} Developed By Ihtisham Ali - Shadow Walker ${reset}"



#Code Start From Here



echo "${bt}"
echo "${cyan}$bt • YouTube: ${yellow}https://youtube.com/ShadowWalkerYT"

echo "${cyan} $bt• GitHub: ${yellow}https://github.com/ShadowWalker005"

echo "${cyan} $bt• Facebook: ${yellow}https://facebook.com/ShadowWalkerYT"

echo "${cyan}$bt • Blogspot: ${yellow}https://shadowhub.blogspot.com"
echo "${cyan}$bt • Telegram: ${yellow}https://t.me/ShadowWalkerYT"


echo "$reset"

echo "${white}${rbg}${bt} • Set A Password For Login ${reset}"
echo
read -p "${green} ➤ ${cyan}${bt}Type Old Password: " oldpass
echo
read -p "${green} ➤ ${cyan}${bt}Type New Password: " newpass

echo
echo
read -p "${white} • ${green}Hit Enter To Activate... "
sed -i "s/$oldpass/$newpass/g" $PREFIX/bin/login_t
xdg-open https://youtube.com/ShadowWalkerYT
echo
echo

echo "${white}${rbg}${bt} SUBSCRIBE - SHADOW WALKER ${reset}"
echo

